# --- Large-Cap Strategy Config (BTC建て) ---
universe_ids:
  - ethereum
  - binancecoin
  - solana
  - ripple
  - cardano
  - dogecoin
  - tron
  - avalanche-2
  - chainlink
  - toncoin
  - polkadot
  - polygon
  - litecoin

# 重み（短期寄り推奨）
weights:
  pct_1h_btc: 0.50
  pct_24h_btc: 0.35
  pct_7d_btc: 0.15

use_volume_factor: true      # USD出来高をボーナス加点
volume_factor_weight: 0.10

top_n: 20
out_csv: largecap_strength_btc.csv
out_png: largecap_strength_btc.png

universe_mode: top_mcap     # manual / top_mcap
top_mcap_n: 20
# ここは USD だけの追加除外・追加採用（任意）
exclude_ids:
  - paypal-usd        # USD系の新顔
  - euro-coin         # EURステーブル
include_ids: []       # どうしても入れたい id があればここに
