# --- Large-Cap Strategy Config ---
universe_ids:
  - bitcoin
  - ethereum
  - binancecoin
  - solana
  - ripple
  - cardano
  - dogecoin
  - tron
  - avalanche-2
  - chainlink
  - toncoin

weights:
  pct_1h: 0.40
  pct_24h: 0.40
  pct_7d: 0.20

use_volume_factor: true
volume_factor_weight: 0.10

top_n: 20
out_csv: largecap_strength.csv
out_png: largecap_strength.png

# ▼追加
universe_mode: top_mcap      # manual / top_mcap
top_mcap_n: 20               # 何銘柄採用するか
exclude_ids:                 # 常に除外したい CoinGecko id（推奨）
  - tether
  - usd-coin
  - binance-usd
  - dai
  - true-usd
  - first-digital-usd
  - frax
  - usdd
  - terrausd
  - wrapped-bitcoin
  - staked-ether
include_ids: []              # どうしても含めたい id（任意）
