# --- Large-Cap Strategy Config ---
universe_ids:
  - bitcoin
  - ethereum
  - binancecoin
  - solana
  - ripple
  - cardano
  - dogecoin
  - tron
  - avalanche-2
  - chainlink
  - toncoin

weights:
  pct_1h: 0.40
  pct_24h: 0.40
  pct_7d: 0.20

use_volume_factor: true
volume_factor_weight: 0.10

top_n: 10
out_csv: largecap_strength.csv
out_png: largecap_strength.png
