# --- Large-Cap Strength (USD vs BTC) Compare ---

# config_largecap_compare.yaml
universe_mode: top_mcap      # ← 追加
top_mcap_n: 20               # ← ここを20に
exclude_ids:                 # ← ステーブル等を除外
compare_select: or              # 説明用のフラグ（使ってなくてもOK）
compare_source_topn: 30         # 片側の参照TopN
compare_top_n: 20               # 最終表示数
compare_guard_min: 0.0          # 両軸の最低z（例: 0 or -0.2）
compare_penalty_lambda: 0.3     # 不均衡ペナルティ 0〜0.6目安

include_ids: []              # 強制的に入れたいIDがあればここに
# （既存の weights 等はそのままでOK）
weights_usd:
  pct_1h: 0.40
  pct_24h: 0.40
  pct_7d: 0.20
use_volume_factor_usd: true
volume_factor_weight_usd: 0.10

weights_btc:
  pct_1h_btc: 0.50
  pct_24h_btc: 0.35
  pct_7d_btc: 0.15
use_volume_factor_btc: true
volume_factor_weight_btc: 0.10

threshold_usd: 0.0
threshold_btc: 0.0

out_csv: largecap_compare.csv
out_png_scatter: largecap_usd_vs_btc.png
