# --- Large-Cap Strategy Config ---
universe_ids:

weights:
  pct_1h: 0.40
  pct_24h: 0.40
  pct_7d: 0.20

use_volume_factor: true
volume_factor_weight: 0.10

top_n: 20
out_csv: largecap_strength.csv
out_png: largecap_strength.png

universe_mode: top_mcap     # manual / top_mcap
top_mcap_n: 21

# ここは USD だけの追加除外・追加採用（任意）
exclude_ids:
include_ids: []       # どうしても入れたい id があればここに
