USDE: ethena-usde
WETH: weth
WEETH: wrapped-eeth
WBETH: wrapped-beacon-eth
WSTETH: wrapped-steth
STETH: staked-ether
USDT: tether
USDC: usd-coin
BUSD: binance-usd
DAI: dai
FDUSD: first-digital-usd
PYUSD: paypal-usd
EURC: euro-coin
FRAX: frax
USDD: usdd
LEO: leo-token
CBBTC: coinbase-wrapped-btc
SUSDE: ethena-staked-usde
UNISTETH: unistake
WBT:
  - wrapped-bitcoin
  - whitebit
BSC-USD: binance-bridged-usdt-bnb-smart-chain
USDS:
  - sperax-usd
  - usds
