name: LargeCap Daily to Discord

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"   # 09:00 JST

jobs:
  run-and-send:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      MPLBACKEND: Agg

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      # yq をインストール
      - name: Install yq
        run: |
          curl -L https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
          /usr/local/bin/yq --version

      # .env を以降の全ステップで使えるように登録
      - name: Export .env to GITHUB_ENV
        run: |
          sed -e 's/\r$//' .github/workflows/largecap-watch.env \
            | grep -v '^\s*#' >> "$GITHUB_ENV"
          echo "LARGECAP_EXCLUDE=${LARGECAP_EXCLUDE:-UNSET}"

      # effective 設定を4つ作成（exclude_ids を必ず配列で注入）
      - name: Build effective configs (force exclude_ids)
        run: |
          set -euo pipefail
          for base in \
              config_largecap.yaml \
              config_largecap_btc.yaml \
              config_largecap_compare.yaml \
              config_largecap_compare_scheduler.yaml; do
            out="${base%.yaml}.effective.yaml"
            echo "making $out from $base"
            /usr/local/bin/yq '
              .exclude_ids = (.exclude_ids // [])
                             + ((env(LARGECAP_EXCLUDE) // "[]") | fromjson)
              | .exclude    = .exclude_ids
            ' "$base" > "$out"
            echo -n "$out => exclude_ids: "; /usr/local/bin/yq '.exclude_ids' "$out"
          done

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt || pip install -U requests pyyaml pandas matplotlib

      - name: Run USD strength (top_n from YAML)
        run: |
          python largecap_strength.py --config config_largecap.effective.yaml
          ls -l largecap_strength.*

      - name: Pause to avoid 429
        run: sleep 12

      - name: Run BTC strength (top_n from YAML)
        run: |
          python largecap_strength_btc.py --config config_largecap_btc.effective.yaml
          ls -l largecap_strength_btc.*

      # USD/BTC strength の後
      - name: Pause to avoid 429 (random)
        run: |
          python - <<'PY'
          import random, time
          wait = 60 + random.randint(0,30)
          print(f"sleep {wait}s to avoid 429"); time.sleep(wait)
          PY

      # --- Compare & send to Discord ---
      - name: Run compare & send to Discord (with trails)
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python run_compare_scheduler.py \
            --config config_largecap_compare_scheduler.effective.yaml \
            --repeat 1 --trails --hours 168 --topn 20 --smooth 5 \
            --webhook-url "$WEBHOOK" --label "LargeCap Daily (USD×BTC)"

      # 作られた PNG / CSV を確認（デバッグ）
      - name: List generated PNG/CSV
        run: |
