- name: Ping Discord (text only)
  env:
    WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
  run: |
    # Secret が入っているかを確認
    if [ -z "${WEBHOOK:-}" ]; then
      echo "WEBHOOK is EMPTY (Actions Secrets not set?)"
      exit 1
    fi
    echo "WEBHOOK length = $(printf %s "${WEBHOOK}" | wc -c)"
    # テキストだけ送ってみる
    curl -sS -X POST -H "Content-Type: application/json" \
      -d "{\"content\":\"Ping from GitHub Actions $(date -u)\"}" "$WEBHOOK"
