name: LargeCap Daily to Discord

on:
  schedule:
    - cron: "*/5 * * * *"   # ← 半角の */5
  workflow_dispatch: {}


jobs:
  run-and-send:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # 履歴CSVをdata/にコミットする場合だけ必要
    env:
      MPLBACKEND: Agg
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run compare & send to Discord (with trails)
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}
        run: |
          python run_compare_scheduler.py --repeat 1 --trails --hours 168 --topn 12 --smooth 5 \
            --webhook-url "$WEBHOOK" --label "LargeCap Daily (USD×BTC)"

      # （任意）履歴CSVをコミットして貯める
      - name: Save snapshot CSVs to repo
        run: |
          mkdir -p data
          ls -1 largecap_compare_*.csv 2>/dev/null | xargs -I{} cp "{}" data/ || true
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/*.csv
          git commit -m "snapshot: $(date -u +%F_%H%M)" || echo "No changes"
          git push
