name: LargeCap (shared)

on:
  workflow_call:
    inputs:
      send_discord:
        type: boolean
        default: true
      python-version:
        type: string
        default: '3.11'
    secrets:
      DISCORD_WEBHOOK_URL:
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    timeout-minutes: 25        # ← ここに置く（全呼び出しに適用）
    permissions:
      contents: write
    env:
      MPLBACKEND: Agg           # ← これをJobに入れておくと安心
      
    steps:
      # 1) リポジトリ取得
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      # ★ 追加（checkout 直後）
      - name: Sync repo (pull latest)
        run: |
          git config --global pull.rebase true
          git pull --rebase --autostash || true

      # 2) Python 準備
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python-version }}
          cache: pip

      # 3) yq（念のため）
      - name: Install yq
        run: |
          curl -L https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq
          /usr/local/bin/yq --version

      # 4) 除外リストを注入して *.effective.yaml を生成（← ここが“アクションの呼び出し”）
      #    事前に .github/actions/build-effectives/action.yml を置いてある前提
      - name: Build effective configs (inject excludes)
        uses: ./.github/actions/build-effectives
        with:
          env-file: .github/workflows/largecap-watch.env
          configs: |
            config_largecap.yaml
            config_largecap_btc.yaml
            config_largecap_compare.yaml

      - name: Sanity check excludes (15m)
        run: |
          python - <<'PY'
          import os, json, yaml, pathlib  # ← requests を消す
          cfgs = [
              "config_largecap.effective.yaml",
              "config_largecap_btc.effective.yaml",
              "config_largecap_compare.effective.yaml",
          ]
          for p in cfgs:
              if not pathlib.Path(p).exists():
                  print(f"[CFG] skip {p} (not found)")
                  continue
              y = yaml.safe_load(open(p, encoding="utf-8")) or {}
              ex = y.get("exclude_ids") or []
              print(f"[CFG] {p}: exclude_ids={len(ex)}")
          PY

      
      # 5) 依存
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt || pip install -U requests pyyaml pandas matplotlib

      # 6) 強弱（USD）
      #       - name: Run USD strength (15m)
      #       run: |
      #        python largecap_strength.py --config config_largecap.effective.yaml

      # 7) 429回避
      - name: Pause to avoid 429
        run: sleep 8

      # 8) 強弱（BTC建て）
      # - name: Run BTC strength (15m)
      #     run: |
      #       python largecap_strength_btc.py --config config_largecap_btc.effective.yaml

      # 9) USD×BTC 比較（トレイルも内部で更新される想定）
      - name: Run compare
        run: |
          python compare_strength.py --config config_largecap_compare.effective.yaml


      - name: Inspect trails files (do we have today?)
        shell: bash
        run: |
          set -euo pipefail
      
          echo "== ls -l data =="
          ls -l data || true
      
          echo "== grep today (UTC & JST-like) =="
          d_utc=$(date -u +%Y-%m-%d)
          d_jst=$(TZ=Asia/Tokyo date +%Y-%m-%d)
          echo "look for $d_utc or $d_jst"
          for f in data/score_trails_*.csv ; do
            echo "-- $f"
            (grep -n "$d_utc" "$f" || true) | tail -n 3
            (grep -n "$d_jst" "$f"  || true) | tail -n 3
          done
      
          echo "== pandas view =="
          python - <<'PY'
          import pandas as pd, pathlib
          from zoneinfo import ZoneInfo
          JST = ZoneInfo("Asia/Tokyo")
          
          for side in ("usd","btc"):
              p = pathlib.Path("data")/f"score_trails_{side}.csv"
              if not p.exists():
                  print("[MISS]", p)
                  continue
              df = pd.read_csv(p)
              ts = pd.to_datetime(df["ts"], errors="coerce", utc=True)
              ok = ts.notna().sum()
              mx = str(ts.dropna().max())
              print(f"[{side}] rows={len(df)}  parsed={ok}  max_ts={mx}")
              print(df.tail(3).to_string(index=False))
          PY


      - name: Send charts to Discord
        if: ${{ inputs.send_discord && env.WEBHOOK != '' }}
        continue-on-error: true
        env:
          # 旧名/新名どちらでもOKにするフォールバック
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL || secrets.DISCORD_WEBHOOK }}
        shell: bash
        run: |
          set -euo pipefail
          shopt -s globstar nullglob

          usd=(**/largecap_usd_vs_btc.png)
          t1=(**/score_trails_usd.png)
          t2=(**/score_trails_btc.png)
          t3=(**/score_trails_usdxbtc.png)        
          s_usd=(**/largecap_strength.png)
          s_btc=(**/largecap_strength_btc.png)
      
          : "${usd:?missing usd_vs_btc.png}"
          : "${t1:?missing score_trails_usd.png}"
          : "${t2:?missing score_trails_btc.png}"
          : "${t3:?missing score_trails_usdxbtc.png}"        
          : "${s_usd:?missing largecap_strength.png}"
          : "${s_btc:?missing largecap_strength_btc.png}"
    
       
          msg="LargeCap 15m — $(date -u +'%Y-%m-%d %H:%M UTC')"
          payload=$(printf '{"content":"%s"}' "$msg")
      
          curl -sS -f -X POST \
            -F "payload_json=$payload" \
            -F "file1=@${usd[0]};type=image/png" \
            -F "file2=@${t1[0]};type=image/png" \
            -F "file3=@${t2[0]};type=image/png" \        
            -F "file4=@${s_usd[0]};type=image/png" \
            -F "file5=@${s_btc[0]};type=image/png" \
            -F "file6=@${t3[0]};type=image/png" \
            "$WEBHOOK"
            
      - name: Inspect trails files (do we have today?)
        shell: bash
        run: |
          set -euo pipefail
          echo "== ls -l data =="
          ls -l data || true
      
          echo "== grep today (UTC & JST-like) =="
          d_utc=$(date -u +%Y-%m-%d)          # 例 2025-08-24
          d_jst=$(TZ=Asia/Tokyo date +%Y-%m-%d)
          echo "look for $d_utc or $d_jst"
          for f in data/score_trails_*.csv ; do
            echo "-- $f"
            (grep -n "$d_utc" "$f" || true) | tail -n 3
            (grep -n "$d_jst" "$f"  || true) | tail -n 3
          done
      
      
      - name: Debug show latest trail rows
        shell: bash
        run: |
          set -euo pipefail
          echo "== tail USD =="
          tail -n 3 data/score_trails_usd.csv || true
          echo "== tail BTC =="
          tail -n 3 data/score_trails_btc.csv || true

      # 11) 生成物をコミット
      - name: Commit & push artifacts
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
          files=()
          for f in largecap_*.png largecap_*.csv score_trails_*.png data/score_trails_*.csv; do
            [[ -e "$f" ]] && files+=("$f")
          done
          (( ${#files[@]} )) || { echo "No artifacts to commit"; exit 0; }
          echo "Will commit: ${files[*]}"
          git config user.name  github-actions
          git config user.email github-actions@github.com
          git add -- "${files[@]}"
          git commit -m "Update trails $(date -u +'%Y-%m-%dT%H:%MZ')" || exit 0
          git pull --rebase
          git push
