name: Largecap Daily

on:
  workflow_dispatch:
  schedule:
    - cron: "*/60 * * * *"

# ← これを追加（または下の jobs.run.permissions に置いてもOK）
permissions:
  contents: write

concurrency:
  group: largecap-Daily
  cancel-in-progress: true

jobs:
  run:
    # ここはそのままでOK（同一リポは ref 指定不要）
    uses: ./.github/workflows/largecap-shared.yml
    secrets:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
    with:
      # 送信ON/OFF（shared 側 inputs に合わせる）
      send_discord: true
      trails_keep_hours: 8760   # 例：365日保持
      # Python のバージョンを上書きしたい場合（任意）
      python-version: '3.11'
