# .github/workflows/schedule_smoke.yml
name: schedule-smoke
on:
  schedule:
    - cron: "*/5 * * * *"   # ← 5分おき（UTC基準）
  workflow_dispatch: {}      # ← 手動実行ボタン
jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "EVENT=$GITHUB_EVENT_NAME"
          date -u
