name: Trails Feeder (15m)

on:
  workflow_dispatch:
  schedule:
    - cron: '*/60 * * * *'   # 15分ごと

concurrency:
  group: largecap-15m
  cancel-in-progress: true

jobs:
  trails:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      MPLBACKEND: 'Agg'
      LARGECAP_EXCLUDE: '[]'                       # 未設定でも [] に
      WEBHOOK: ${{ secrets.DISCORD_WEBHOOK_URL }}   # ← ここを統一

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0   # ← rebase/pull に必要

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      # compare_strength.py は PyYAML / pandas / matplotlib / requests 等が必要
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -U pyyaml requests pandas numpy matplotlib

      - name: Install yq
        run: |
          sudo curl -L https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      - name: Load env & inject excludes
        shell: bash
        run: |
          set -euo pipefail
          ENV_FILE="${GITHUB_WORKSPACE}/.github/workflows/largecap-watch.env"
          [ -f "$ENV_FILE" ] || { echo "::error::env file not found: $ENV_FILE"; exit 1; }
      
          # .env → GITHUB_ENV（コメント/空行と DISCORD_WEBHOOK を除外）
          sed -e 's/\r$//' "$ENV_FILE" \
            | grep -Ev '^[[:space:]]*($|#)|^(DISCORD_WEBHOOK|WEBHOOK)=' >> "$GITHUB_ENV"

      
          echo "[LOG] LARGECAP_EXCLUDE=${LARGECAP_EXCLUDE:-[]}"
      
          # ←← ここから「cat >> 一時ファイル」方式（YAMLのインデントに左右されない）
          cat > /tmp/update_excludes.py <<'PY'
          import os, json, re, yaml, pathlib
      
          # env → 配列（壊れていれば []）
          try:
              ex = json.loads(os.environ.get("LARGECAP_EXCLUDE", "[]") or "[]")
              if not isinstance(ex, list):
                  ex = []
          except Exception:
              ex = []
          
          files = [
              "config_largecap.yaml",
              "config_largecap_btc.yaml",
              "config_largecap_compare.yaml",
              "config_largecap_compare_scheduler.yaml",
          ]
          
          for f in files:
              p = pathlib.Path(f)
              if not p.exists():
                  continue
              txt = p.read_text(encoding="utf-8")
              # 「exclude_ids:\n[]」の崩れを補正
              txt = re.sub(r'(?m)^exclude_ids:\s*\n\[\]\s*(?=\n|$)', 'exclude_ids: []', txt)
          
              data = yaml.safe_load(txt) or {}
              data["exclude_ids"] = ex
              p.write_text(
                  yaml.safe_dump(data, allow_unicode=True, sort_keys=False),
                  encoding="utf-8"
              )
              print("[OK] updated", f)
          PY
          
              python /tmp/update_excludes.py



      - name: Run compare (15m)
        shell: bash
        run: |
          set -euo pipefail
          python compare_strength.py --config config_largecap_compare.yaml

      - name: Run USD strength (15m)
        shell: bash
        run: |
          set -euo pipefail
          python largecap_strength.py --config config_largecap.effective.yaml
          stamp=$(TZ=Asia/Tokyo date +'%Y%m%d_%H%M')
          cp -f largecap_strength.png "largecap_strength_usd_${stamp}.png"

      - name: Pause to avoid 429
        run: |
          sleep $(( 15 + RANDOM % 30 ))

      - name: Run BTC strength (15m)
        shell: bash
        run: |
          set -euo pipefail
          # 連続叩きの 429 回避に少し待つ（任意）
          sleep 8
          python largecap_strength_btc.py --config config_largecap_btc.effective.yaml
          stamp=$(TZ=Asia/Tokyo date +'%Y%m%d_%H%M')
          cp -f largecap_strength_btc.png "largecap_strength_btc_${stamp}.png"



      - name: List artifacts (debug)
        if: ${{ env.DEBUG == '1' || failure() }}
        shell: bash
        run: |
          set -euo pipefail
          echo "PWD=$(pwd)"
          shopt -s globstar nullglob
          for f in **/largecap_usd_vs_btc.png **/score_trails_*.png **/largecap_compare.csv **/data/score_trails_*.csv; do
            [ -e "$f" ] && ls -lh "$f"
          done
      
      - name: Send 5 charts to Discord (15m)
        if: ${{ env.WEBHOOK }}
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob globstar
      
          # 1) webhook を念のためトリム
          W=$(printf '%s' "${WEBHOOK}" | tr -d '\r' \
              | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//' \
                    -e "s/^['\"]//" -e "s/['\"]$//")
      
          # 2) ファイルを“明示”で探す（最新版優先）
          quad=$(ls -t **/largecap_usd_vs_btc*.png 2>/dev/null | head -1 || true)
          trails_usd=$(ls -t **/score_trails_usd*.png 2>/dev/null | head -1 || true)
          trails_btc=$(ls -t **/score_trails_btc*.png 2>/dev/null | head -1 || true)
          # USD の強弱は古い命名（largecap_strength.png）と将来の命名（largecap_strength_usd*.png）の両方を許容
          strength_usd=$(ls -t **/largecap_strength.png **/largecap_strength_usd*.png 2>/dev/null | head -1 || true)
          strength_btc=$(ls -t **/largecap_strength_btc*.png 2>/dev/null | head -1 || true)
      
          echo "quad=$quad"
          echo "trails_usd=$trails_usd"
          echo "trails_btc=$trails_btc"
          echo "strength_usd=$strength_usd"
          echo "strength_btc=$strength_btc"
      
          files=()
          [[ -f "$quad"         ]] && files+=("$quad")
          [[ -f "$trails_usd"   ]] && files+=("$trails_usd")
          [[ -f "$trails_btc"   ]] && files+=("$trails_btc")
          [[ -f "$strength_usd" ]] && files+=("$strength_usd")
          [[ -f "$strength_btc" ]] && files+=("$strength_btc")
      
          # 3) 内容ハッシュで重複排除（BTC画像の二重送信を防止）
          declare -A H=()
          uniq=()
          for f in "${files[@]}"; do
            h=$(sha1sum "$f" | awk '{print $1}')
            if [[ -z "${H[$h]+x}" ]]; then
              uniq+=("$f"); H[$h]=1
            else
              echo "dup: $f (skip)"
            fi
          done
      
          (( ${#uniq[@]} )) || { echo "::warning::No charts to send"; exit 0; }
      
          # 4) 送信
          msg="LargeCap 15m — $(date -u +'%Y-%m-%d %H:%M UTC')"
          payload=$(printf '{"content":"%s"}' "$msg")
      
          FORM=()
          for i in "${!uniq[@]}"; do
            n=$((i+1))
            FORM+=("-F" "file${n}=@${uniq[$i]};type=image/png")
          done
      
          curl -sS -f -X POST -F "payload_json=$payload" "${FORM[@]}" "$W"







      - name: Debug webhook
        run: |
          if [ -n "${WEBHOOK:-}" ]; then echo "WEBHOOK: set"; else echo "WEBHOOK: EMPTY"; fi


          
      - name: Commit & push trails
        shell: bash
        run: |
          set -euo pipefail
          shopt -s nullglob
      
          # 生成物収集（あなたのロジックのままでOK）
          files=()
          [[ -f largecap_usd_vs_btc.png ]] && files+=("largecap_usd_vs_btc.png")
          # ★ 強弱PNG（USD/BTC）を追加
          [[ -f largecap_strength.png ]] && files+=("largecap_strength.png")
          [[ -f largecap_strength_btc.png ]] && files+=("largecap_strength_btc.png")

          for f in score_trails_*.png data/score_trails_*.csv largecap_compare.csv; do
            [[ -e "$f" ]] && files+=("$f")
          done
      
          (( ${#files[@]} )) || { echo "No artifacts to commit"; exit 0; }
      
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
      
          # リモートを取り込み → rebase → 追加 → commit → push（最大3回リトライ）
          git fetch origin main
          git checkout -B main origin/main
      
          git add -- "${files[@]}"
          if git diff --cached --quiet; then
            echo "Nothing to commit"; exit 0
          fi
          git commit -m "Update trails $(date -u +'%Y-%m-%dT%H:%MZ')"
          # 衝突回避（fast-forwardできない場合）
          git pull --rebase --autostash origin main || true
          git push
          
          for i in 1 2 3; do
            if git push origin HEAD:main; then
              echo "Pushed successfully"; exit 0
            fi
            echo "Push rejected (non-ff). Retry $i: rebase onto origin/main ..."
            git fetch origin main
            git rebase origin/main || { echo "Rebase conflict. Falling back to merge-fastforward attempt"; git reset --hard; git pull --ff-only || true; }
          done
      
          echo "::error::Failed to push after retries"
          exit 1
      
