name: Trails Feeder (15m)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"   # 15分ごと（お好みで 10/30分などに変更可）

jobs:
  trails:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      MPLBACKEND: Agg
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"

      # yq は exclude_ids 注入に使う（daily と同じ設定を踏襲）
      - name: Install yq
        run: |
          curl -L https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Load env & inject excludes
      shell: bash
      run: |
        set -euo pipefail
        set -a
        source .github/workflows/largecap-watch.env
        set +a

        FILES="config_largecap.yaml config_largecap_btc.yaml config_largecap_compare.yaml config_largecap_compare_scheduler.yaml"

        # exclude_ids をあるファイルにだけ注入
        for f in $FILES; do
          [ -f "$f" ] || continue
          /usr/local/bin/yq '
            .exclude_ids = ((.exclude_ids // []) + ((env(LARGECAP_EXCLUDE) | fromjson) // [])) |
            .exclude     = .exclude_ids
          ' "$f" > "$f.tmp" && mv "$f.tmp" "$f"
        done

        # effective をあるファイルだけ生成
        for base in $FILES; do
          [ -f "$base" ] || continue
          /usr/local/bin/yq '.' "$base" > "${base%.yaml}.effective.yaml"
        done

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt || pip install -U pandas matplotlib pyyaml requests

      # Trails だけ更新（Discord送信はしない）
      - name: Update Trails (no Discord)
        run: |
          python run_compare_scheduler.py \
            --config config_largecap_compare_scheduler.effective.yaml \
            --repeat 1 --trails --hours 168 --topn 20 --smooth 5 \
            --label "Trails Feeder"

      # CSV をコミットして履歴を持続
      - name: Commit & push trails
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/score_trails_*.csv data/movers_*.csv || true
          git commit -m "trails: $(date -u +%F_%H%M)" || echo "No changes"
          git push || true
