name: Trails Feeder (15m)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/60 * * * *"

# ← これを追加（または下の jobs.run.permissions に置いてもOK）
permissions:
  contents: write

concurrency:
  group: largecap-15m
  cancel-in-progress: true

jobs:
  run:
    timeout-minutes: 25      # ← 念のための保険
    # ここはそのままでOK（同一リポは ref 指定不要）
    uses: ./.github/workflows/largecap-shared.yml
    secrets: inherit
    with:
      # 送信ON/OFF（shared 側 inputs に合わせる）
      send_discord: true
      # Python のバージョンを上書きしたい場合（任意）
      python-version: '3.11'
