name: Trails Feeder (15m)

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'   # 15分ごと

concurrency:
  group: trails-feeder
  cancel-in-progress: false

jobs:
  trails:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      MPLBACKEND: 'Agg'
      LARGECAP_EXCLUDE: '[]'   # ← 未設定でも [] が入る
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install yq
        run: |
          curl -L https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq



      - name: Load env & inject excludes
        shell: bash
        run: |
          set -euo pipefail
          pip install -q pyyaml   # ←これを最初に追加
          
          # .env があれば読み込む（無ければスキップ）
          set -a
          source .github/workflows/largecap-watch.env || true
          set +a
      
          # 1) LARGECAP_EXCLUDE を JSON として検証（壊れてたら []）
          EX_JSON="$(
          python - <<'PY'
          import os, json, sys
          ex = os.environ.get('LARGECAP_EXCLUDE', '[]')
          try:
                json.loads(ex)
          except Exception:
                ex = '[]'
          sys.stdout.write(ex)
          PY
          )"
          echo "[LOG] exclude = ${EX_JSON}"

          # 2) YAML を Python で安全に更新
          python - <<'PY'
          import os, json, yaml, io
          ex = json.loads(os.environ.get("EX_JSON", "[]"))
          
          files = [
              "config_largecap.yaml",
              "config_largecap_btc.yaml",
              "config_largecap_compare.yaml",
              "config_largecap_compare_scheduler.yaml",
          ]
          
          for f in files:
              if not os.path.exists(f):
                  continue
              with open(f, "r", encoding="utf-8") as fp:
                  data = yaml.safe_load(fp) or {}
              data["exclude_ids"] = ex
              with open(f, "w", encoding="utf-8") as fp:
                  yaml.safe_dump(data, fp, allow_unicode=True, sort_keys=False)
              print("[OK] updated", f)
          PY




      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt || pip install -U pandas matplotlib pyyaml requests

      - name: Update trails + run compare (15m)
        shell: bash
        env:
          WEBHOOK: ${{ secrets.DISCORD_WEBHOOK || '' }}
        run: |
          set -euo pipefail
          echo "[LOG] LARGECAP_EXCLUDE=${LARGECAP_EXCLUDE:-[]}"
      
          # Trails CSV→PNG 更新
          python history_aggregate.py
          python plot_score_trails.py --metric btc --hours 168 --topn 20 --smooth 3
          python plot_score_trails.py --metric usd --hours 168 --topn 20 --smooth 3
      
          # 比較本体（--trails 等の未知オプションは付けない）
          python compare_strength.py --config config_largecap_compare.yaml


      - name: Commit & push trails
        shell: bash
        run: |
          set -e
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # ← ここを“movers_*”ではなく trails の実ファイルに
          git add data/score_trails_*.csv || true
          git add score_trails_*.png     || true

          # （必要なら比較PNG/CSVも一緒に）
          git add largecap_usd_vs_btc_*.png  || true

          echo "--- staged changes ---"
          git status --porcelain

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "trails: $(TZ=Asia/Tokyo date +'%F %H:%M JST')"
            git push
          fi
