name: Trails Feeder (15m)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

concurrency:
  group: largecap-15m
  cancel-in-progress: true

jobs:
  run:
    uses: ./.github/workflows/largecap-shared.yml
    secrets: inherit
    with:
      send_discord: true   # 15分でも送るなら true。不要なら false か削除

