name: Trails Feeder (15m)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/15 * * * *"

# ← これを追加（または下の jobs.run.permissions に置いてもOK）
permissions:
  contents: write

concurrency:
  group: largecap-15m
  cancel-in-progress: true

jobs:
  run:
    # ここはそのままでOK（同一リポは ref 指定不要）
    uses: ./.github/workflows/largecap-shared.yml
    # Webhook などの secrets を共有
    secrets: inherit
    # （任意）共通WFの inputs を渡す
    with:
      send_discord: true
