name: Trails Feeder (15m)

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'   # 15分ごと

concurrency:
  group: largecap-15m
  cancel-in-progress: true

jobs:
  trails:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      MPLBACKEND: 'Agg'
      LARGECAP_EXCLUDE: '[]'                       # 未設定でも [] に
      DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      # compare_strength.py は PyYAML / pandas / matplotlib / requests 等が必要
      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -U pyyaml requests pandas numpy matplotlib

      - name: Install yq
        run: |
          sudo curl -L https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -o /usr/local/bin/yq
          sudo chmod +x /usr/local/bin/yq

      # .env → GITHUB_ENV（Webhook は除外し、最後に secrets で上書き）
      - name: Load env & inject excludes
        shell: bash
        run: |
          set -euo pipefail
          ENV_FILE="${GITHUB_WORKSPACE}/.github/workflows/largecap-watch.env"
          if [ ! -f "$ENV_FILE" ]; then
            echo "::error::env file not found: $ENV_FILE"; exit 1
          fi
      
          # .env からコメント/空行と DISCORD_WEBHOOK 行を除外して注入
          sed -e 's/\r$//' "$ENV_FILE" \
            | grep -Ev '^[[:space:]]*($|#)|^DISCORD_WEBHOOK=' >> "$GITHUB_ENV"
      
          # secrets で確実に上書き（空上書き防止）
          echo "DISCORD_WEBHOOK=${{ secrets.DISCORD_WEBHOOK }}" >> "$GITHUB_ENV"
      
          echo "[LOG] LARGECAP_EXCLUDE=${LARGECAP_EXCLUDE:-[]}"
      
          # exclude_ids を一括更新（LARGECAP_EXCLUDE が壊れてても [] にフォールバック）
          for f in config_largecap.yaml config_largecap_btc.yaml \
                   config_largecap_compare.yaml config_largecap_compare_scheduler.yaml
          do
            [ -f "$f" ] || continue
            yq -i '.exclude_ids = (env(LARGECAP_EXCLUDE) | fromjson? // [])' "$f"
            echo "[OK] updated $f"
          done


      - name: Run compare (15m)
        shell: bash
        run: |
          set -euo pipefail
          python compare_strength.py --config config_largecap_compare.yaml

      - name: List artifacts (debug)
        if: ${{ env.DEBUG == '1' || failure() }}
        shell: bash
        run: |
          set -euo pipefail
          echo "PWD=$(pwd)"
          shopt -s globstar nullglob
          for f in **/largecap_usd_vs_btc.png **/score_trails_*.png **/largecap_compare.csv **/data/score_trails_*.csv; do
            [ -e "$f" ] && ls -lh "$f"
          done

      - name: Send 3 charts to Discord (15m)
        shell: bash
        run: |
          set -euo pipefail
          if [ -z "${DISCORD_WEBHOOK:-}" ]; then
            echo "::notice::DISCORD_WEBHOOK is empty; skip sending."; exit 0
          fi
          shopt -s globstar nullglob
          usd=(**/largecap_usd_vs_btc.png)
          t1=(**/score_trails_usd.png)
          t2=(**/score_trails_btc.png)
          : "${usd:?missing largecap_usd_vs_btc.png}"
          : "${t1:?missing score_trails_usd.png}"
          : "${t2:?missing score_trails_btc.png}"
          msg="LargeCap 15m — $(date -u +'%Y-%m-%d %H:%M UTC')"
          payload=$(printf '{"content":"%s"}' "$msg")
          curl -sS -f -X POST \
            -F "payload_json=$payload" \
            -F "file1=@${usd[0]};type=image/png" \
            -F "file2=@${t1[0]};type=image/png" \
            -F "file3=@${t2[0]};type=image/png" \
            "$DISCORD_WEBHOOK"

      - name: Commit & push trails
        shell: bash
        run: |
          set -euo pipefail
          shopt -s globstar nullglob
          files=(**/largecap_usd_vs_btc.png **/score_trails_*.png **/largecap_compare.csv **/data/score_trails_*.csv)
          (( ${#files[@]} )) || { echo "No artifacts to commit"; exit 0; }
          git config user.name  github-actions
          git config user.email github-actions@github.com
          git add -- "${files[@]}"
          if git diff --cached --quiet; then
            echo "Nothing to commit"; exit 0
          fi
          git commit -m "Update trails $(date -u +'%Y-%m-%dT%H:%MZ')"
          git push
