name: Trails Feeder (15m)

on:
  workflow_dispatch:
  schedule:
    - cron: '*/15 * * * *'   # 15分ごと

concurrency:
  group: trails-feeder
  cancel-in-progress: false

jobs:
  trails:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    env:
      MPLBACKEND: 'Agg'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install yq
        run: |
          curl -L https://github.com/mikefarah/yq/releases/download/v4.44.3/yq_linux_amd64 -o /usr/local/bin/yq
          chmod +x /usr/local/bin/yq

      - name: Load env & inject excludes
        shell: bash
        run: |
          set -euo pipefail
          set -a
          source .github/workflows/largecap-watch.env
          set +a

          FILES="config_largecap.yaml config_largecap_btc.yaml config_largecap_compare.yaml config_largecap_compare_scheduler.yaml"

          # あるファイルにだけ exclude_ids を注入
          for f in $FILES; do
            if [ -f "$f" ]; then
              /usr/local/bin/yq '
                .exclude_ids = ((.exclude_ids // []) + ((env(LARGECAP_EXCLUDE) | fromjson) // [])) |
                .exclude     = .exclude_ids
              ' "$f" > "$f.tmp" && mv "$f.tmp" "$f"
            fi
          done

          # あるファイルだけ effective を生成
          for base in $FILES; do
            if [ -f "$base" ]; then
              /usr/local/bin/yq '.' "$base" > "${base%.yaml}.effective.yaml"
            fi
          done

          echo "Prepared effective configs:"
          ls -1 *.effective.yaml || true

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt || pip install -U pandas matplotlib pyyaml requests

      - name: Update Trails(no discord)
        shell: bash
        run: |
          set -euo pipefail
          # compare 用の effective を優先して使う
          CFG="config_largecap_compare.effective.yaml"
          if [ ! -f "$CFG" ]; then
            echo "::error::No compare config found (config_largecap_compare*.effective.yaml)."
            exit 1
          fi
          echo "Using config: $CFG"
          python compare_strength.py \
            --config "$CFG" \
            --trails --hours 168 --topn 20 --smooth 5 \
            --label "Trails Feeder"


      - name: Commit & push trails
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add data/score_trails_*.csv data/movers_*.csv || true
          git commit -m "trails: $(date -u +%F_%H%M)" || echo "No changes"
          git push || true
